### ISSUE TITLE
Incorrect font used in the mobile app

### ISSUE THREAD

**Issue by dschoenbauer** [Project-Friendship/PFMobileAppV2#6]
There are 3 fonts used in the mobile app today that have nothing to do with the branding for Project Friendship. 

Replacement should be as follows: 

| Old Font| New Font |
|--------|--------|
| DMSans-Bold | Vision Heavy |
| DMSans-Medium | Vision |
| DMSans-Regular | Vision Light | 

Please note that the update should include the removal of the old font files, the addition of the new font files, and the changing of the reference of the fonts in the code.

Online references: 
- [DaFont](https://www.dafontfree.io/vision-font-family/)
- [Fonts Repo](https://fontsrepo.com/vision-free-font-family-12-fonts/)

**Comment by ethanash** [comment]
https://github.com/Project-Friendship/PFMobileAppV2/tree/6-incorrect-font-used-in-the-mobile-app
